### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './model_save_default/model.pth

### ISSUE THREAD

**Issue by poochat** [breezeyuner/DiffCDR#2]
```ssh
IndexError: list index out of range
(FedFed) PS E:\apple2024\myDiffuRec\myDiffCDR> python entry.py --exp_part diff_CDR --task 1 --base_model MF --seed 1 --gpu 0 --epoch 10 --lr 0.01 --save_path ./model_save_default/model.pth
task:1; model:MF; ratio:[0.8, 0.2]; epoch:10; lr:0.01; gpu:0; seed:1;
diff_steps:1000;diff_sample_steps:30;diff_scale:0.1;diff_dim:128;diff_task_lambda:0.1;
测试
========Reading data========
src 6631 iter / batchsize = 256 
tgt 3927 iter / batchsize = 256 
meta 2935 iter / batchsize = 128 
map 226 iter / batchsize = 64 
diff 2935 iter / batchsize = 128 
aug 10557 iter / batchsize = 256 
ss 5869 iter / batchsize = 64 
E:\apple2024\myDiffuRec\myDiffCDR\run.py:217: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

  full_uid['mask_src'] = 1
la 5869 iter / batchsize = 64
test 10 iter / batchsize = 10240
diff 10 iter / batchsize = 10240
Traceback (most recent call last):
  File "entry.py", line 81, in <module>
    Run(config).main(args.exp_part,args.save_path)
  File "E:\apple2024\myDiffuRec\myDiffCDR\run.py", line 619, in main
    self.model_load(model,path =  save_path )
  File "E:\apple2024\myDiffuRec\myDiffCDR\run.py", line 545, in model_load
    model.load_state_dict(torch.load(path))
  File "D:\anaconda3\envs\FedFed\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\anaconda3\envs\FedFed\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\anaconda3\envs\FedFed\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './model_save_default/model.pth'
(FedFed) PS E:\apple2024\myDiffuRec\myDiffCDR> python entry.py --exp_part diff_CDR
task:1; model:MF; ratio:[0.8, 0.2]; epoch:1; lr:0.01; gpu:0; seed:1;
diff_steps:1000;diff_sample_steps:30;diff_scale:0.1;diff_dim:128;diff_task_lambda:0.1;
测试
========Reading data========
src 6631 iter / batchsize = 256 
tgt 3927 iter / batchsize = 256 
meta 2935 iter / batchsize = 128 
map 226 iter / batchsize = 64 
diff 2935 iter / batchsize = 128 
aug 10557 iter / batchsize = 256 

```

**Comment by fxc135161** [comment]
I also encountered the same issue. Could you please tell me how you solved it? Which model did you use?
